### ISSUE TITLE
chore: setting up prettier, ESLint, husky, and commitlint

### ISSUE THREAD

**Issue by balaji-sivasakthi** [priyankarpal/ProjectsHut#1824]
### What feature?

I would like to set up Prettier, ESLint, Husky, and Commitlint in our project to enforce code formatting, linting, and commit message conventions. This will help maintain a consistent codebase, catch errors early, and improve collaboration within the team.

### Add screenshots

![1](https://github.com/priyankarpal/ProjectsHut/assets/65065614/04d67cfe-0713-49e6-bb5b-0eddf1893ace)
![2](https://github.com/priyankarpal/ProjectsHut/assets/65065614/9821f348-100e-470a-b148-cb7b99612fed)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
@balaji-sivasakthi yeah I agree 💯 we need to enforce code formatting, linting, and commit message conventions. But I have already added PR title checker where we need to follow conventional commits otherwise we are not accepting the PR or changing the PR title. 

Also, after adding we need to update the contributing. 

What do you think @balaji-sivasakthi?

**Comment by priyankarpal** [comment]
> @priyankarpal But here, we have a problem: it only lets them know when they create a PR. However, I will implement Husky in the codebase so that it informs them before raising a PR. Additionally, we can format the code while in the staging area using lint-staged.

yeah sure. we need to do. assigned to you
