### ISSUE TITLE
docs: Project Run

### ISSUE THREAD

**Issue by Harshu467** [priyankarpal/ProjectsHut#1908]
### what's wrong with the documentation?

As of now in Readme there are no steps given how to run this project , a new comer when come on this project will not understand the project and how to run it. We should update Readme file and add all content require to explain steps

### Add screenshots

NA

### Record

- [X] I have checked the existing [issues](https://github.com/priyankarpal/ProjectsHut/issues)
- [X] I have read the [Contributing Guidelines](https://github.com/priyankarpal/ProjectsHut/blob/main/contributing.md)
- [X] I agree to follow this project's [Code of Conduct](https://github.com/priyankarpal/ProjectsHut/blob/main/CODE_OF_CONDUCT.md)
- [X] I'm a GSSoC'23 contributor
- [X] I want to work on this issue

**Comment by priyankarpal** [comment]
we already have the contributing guide & we want README file simple & clear so that user can understand easily. Also, we have mentioned that `Go through the CONTRIBUTING.md file, where all the guidelines have been mentioned that will guide you to make your contribution.` 

I think we don't need to add the `local setup` points here.
